### ISSUE TITLE
Launcher Mess

### ISSUE THREAD

**Issue by Fyoncle** [BramStoutProductions/MiEx#104]
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
	at java.base/java.util.Objects.checkIndex(Unknown Source)
	at java.base/java.util.ArrayList.get(Unknown Source)
	at nl.bramstout.mcworldexporter.world.BiomeRegistry.getBiome(BiomeRegistry.java:74)
	at nl.bramstout.mcworldexporter.export.Exporter.export(Exporter.java:155)
	at nl.bramstout.mcworldexporter.ui.ToolBar$25.actionPerformed(ToolBar.java:837)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

It was working fine yesterday, but today i get black screen in every world i load and they never wanna export and give this log when tried to export.

**Comment by Fyoncle** [comment]
If this gonna help, since my country blocking some games with no reason, i started to use VPN like 2 days ago to play Roblox and stuff, that might be the cause? if it is, then how to fix it? @BramStout

**Comment by BramStout** [comment]
It looks like when you're exporting, that it's trying to get the biome but no biomes have been registered at all. Biomes get added to the registry when loading in a chunk containing biome data. So either no chunks were loaded at all or no chunks that were loaded contained biome data. Since you're saying that you're getting a black screen, that would indicate that no chunks are getting loaded.

The first things to check, is whether there even are actual chunks. When loading in a world, by default it shows the coordinates of 0,0. If there aren't any chunks there, then there is nothing to show or export. Maybe try teleporting to the player to see if that fixes it.

If there should be chunks there, but MiEx isn't showing any, could you then try the following? Open up MiEx, load up a world, try to do another export again, and then share the entire log file? Specifically the entire log file and not an except from it

**Comment by Fyoncle** [comment]
> It looks like when you're exporting, that it's trying to get the biome but no biomes have been registered at all. Biomes get added to the registry when loading in a chunk containing biome data. So either no chunks were loaded at all or no chunks that were loaded contained biome data. Since you're saying that you're getting a black screen, that would indicate that no chunks are getting loaded.
> 
> This has nothing to do with internet, VPNs, or Java Security Access.
> 
> The first things to check, is whether there even are actual chunks. When loading in a world, by default it shows the coordinates of 0,0. If there aren't any chunks there, then there is nothing to show or export. Maybe try teleporting to the player to see if that fixes it.
> 
> If there should be chunks there, but MiEx isn't showing any, could you then try the following? Open up MiEx, load up a world, try to do another export again, and then share the entire log file? Specifically the entire log file and not an except from it

NONE of my worlds work anymore. That is not related to this. That is the **entire** log file that i shared with you.

**Comment by Fyoncle** [comment]
> > > It looks like when you're exporting, that it's trying to get the biome but no biomes have been registered at all. Biomes get added to the registry when loading in a chunk containing biome data. So either no chunks were loaded at all or no chunks that were loaded contained biome data. Since you're saying that you're getting a black screen, that would indicate that no chunks are getting loaded.
> > > This has nothing to do with internet, VPNs, or Java Security Access.
> > > The first things to check, is whether there even are actual chunks. When loading in a world, by default it shows the coordinates of 0,0. If there aren't any chunks there, then there is nothing to show or export. Maybe try teleporting to the player to see if that fixes it.
> > > If there should be chunks there, but MiEx isn't showing any, could you then try the following? Open up MiEx, load up a world, try to do another export again, and then share the entire log file? Specifically the entire log file and not an except from it
> > 
> > 
> > NONE of my worlds work anymore. That is not related to this. That is the **entire** log file that i shared with you.
> 
> The log file provides more information that what you've shared. So please open up MiEx, load in a world, try panning around to get the viewport to redraw itself, close MiEx, and then upload the entire log.txt file in here (you can just drag and drop the log.txt file)

It doesn't provide any logs unless i try to export anything, every world i try to use or even use from exported is blacked out. Only log that it also provides when trying to export is that same lines.

**Comment by Fyoncle** [comment]
MiEx v1.6.2
java.specification.version = 17
os.name = Windows 10
java.specification.vendor = Oracle Corporation
java.version.date = 2024-04-16
java.specification.name = Java Platform API Specification
java.runtime.version = 17.0.11+9
os.version = 10.0
java.runtime.name = OpenJDK Runtime Environment
java.vm.name = OpenJDK 64-Bit Server VM
java.version = 17.0.11
os.arch = amd64
sun.os.patch.level = 

Installing base_resource_pack
Installing base_resource_pack/miex_config.json
Installing base_resource_pack/miex_block_tints.json
Installing base_resource_pack/materials/minecraft/templates/base.json
Installing base_resource_pack/materials/minecraft/templates/emission.json
Installing base_resource_pack/materials/minecraft/templates/grass_block_side.json
Installing base_resource_pack/materials/minecraft/templates/grass_block_snow.json
Installing UsdPreviewSurface/materials/minecraft/templates/base.json
Installing UsdPreviewSurface/materials/minecraft/templates/grass_block_side.json
Installing UsdPreviewSurface/materials/minecraft/templates/water.json
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
	at java.base/java.util.Objects.checkIndex(Unknown Source)
	at java.base/java.util.ArrayList.get(Unknown Source)
	at nl.bramstout.mcworldexporter.world.BiomeRegistry.getBiome(BiomeRegistry.java:74)
	at nl.bramstout.mcworldexporter.export.Exporter.export(Exporter.java:155)
	at nl.bramstout.mcworldexporter.ui.ToolBar$25.actionPerformed(ToolBar.java:837)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)



This again

**Comment by Fyoncle** [comment]
Every vanilla map works, but modded doesn't IF ITS IN THE MODRINTH DIRECTORY, if i move the modded world file into the normal minecraft saves directory it now started working, weird. I never had this before.

**Comment by Fyoncle** [comment]
Can't export modpack resources from modrinth directory either, weird ahhh glitch all of a sudden, it was working a week ago!

**Comment by Fyoncle** [comment]
![image](https://github.com/user-attachments/assets/1193a14c-5da4-4d92-b549-a7f783b5d96a)
Seems like it's because of modrinth changed their file directory...

**Comment by BramStout** [comment]
Does it work if you set the environment variable `MIEX_MODRINTH_ROOT_DIR` in Windows to the `ModrinthApp` folder? MiEx assumes that the root Modrinth folder is `%APPDATA%/com.modrinth.theseus` which it does look like it's now different. Setting that environment variable will allow you to point MiEx to the correct root folder for the Modrinth app

**Comment by Fyoncle** [comment]
> MIEX_MODRINTH_ROOT_DIR

Yep it perfectly fine now, modrinth.theseus is gone completely.

**Comment by BramStout** [comment]
> > MIEX_MODRINTH_ROOT_DIR
> 
> Yep it perfectly fine now, modrinth.theseus is gone completely. Devs are changed this location and moved all the files.

Great to hear! I've updated the default location in the MiEx code so in the next version it should be fixed by default

**Comment by Fyoncle** [comment]
> > > MIEX_MODRINTH_ROOT_DIR
> > 
> > 
> > Yep it perfectly fine now, modrinth.theseus is gone completely. Devs are changed this location and moved all the files.
> 
> Great to hear! I've updated the default location in the MiEx code so in the next version it should be fixed by default

Yeah next version will be released at 2040, perfect :v

**Comment by BramStout** [comment]
> > > > MIEX_MODRINTH_ROOT_DIR
> > > 
> > > 
> > > Yep it perfectly fine now, modrinth.theseus is gone completely. Devs are changed this location and moved all the files.
> > 
> > 
> > Great to hear! I've updated the default location in the MiEx code so in the next version it should be fixed by default
> 
> Yeah next version will be released at 2040, perfect :v

If you want to check the status of the next update, you can have a look at the MiEx To-Do list https://github.com/orgs/BramStoutProductions/projects/1  It's a very big update, so it is taking a while. Also please keep in mind that I am developing it on my own and I also have client work that needs to be done, so developing MiEx is something that I do in between client projects
