### ISSUE TITLE
Channel Not Open For Writing

### ISSUE THREAD

**Issue by Fyoncle** [BramStoutProductions/MiEx#51]
java.io.IOException: Channel not open for writing - cannot extend file to required size
	at java.base/sun.nio.ch.FileChannelImpl.mapInternal(FileChannelImpl.java:1093)
	at java.base/sun.nio.ch.FileChannelImpl.map(FileChannelImpl.java:1032)
	at nl.bramstout.mcworldexporter.world.anvil.ChunkAnvil._load(ChunkAnvil.java:95)
	at nl.bramstout.mcworldexporter.world.Chunk.load(Chunk.java:191)
	at nl.bramstout.mcworldexporter.ui.Renderer2D$LoadChunkTask.run(Renderer2D.java:357)
	at nl.bramstout.mcworldexporter.parallel.ThreadPool$Worker.run(ThreadPool.java:121)
	at java.base/java.lang.Thread.run(Thread.java:840)

I get this log when i load a world and it doesnt load properly.

**Comment by BramStout** [comment]
Would you be able to send me both the entire log.txt file and the world? Then I can try it out on my computer, so that I can try to fix it.

**Comment by Fyoncle** [comment]
> Would you be able to send me both the entire log.txt file and the world? Then I can try it out on my computer, so that I can try to fix it.

Entire log is only says that, and that glitch happens "ONLY" if you're in the world while trying to use MiEx, when you leave the world it fixes.

**Comment by BramStout** [comment]
Unfortunately, it's not possible to load a world into MiEx while it's also loaded into Minecraft. Minecraft is constantly overwriting the world files and MiEx isn't able to handle this well. I have added in a check when opening up a world that it makes sure that it's not loaded by Minecraft.

You can get the latest version of MiEx with this check here: https://github.com/BramStoutProductions/MiEx/releases/tag/v1.6.0
