### ISSUE TITLE
Stay True Resourcepack Log Error

### ISSUE THREAD

**Issue by Fyoncle** [BramStoutProductions/MiEx#66]
When i tried to put Stay True resource pack it gave that log;

Installing base_resource_pack/miex_block_tints.json
Installing UsdPreviewSurface/materials/minecraft/templates/grass_block_side.json
Installing UsdPreviewSurface/materials/minecraft/templates/water.json
java.lang.RuntimeException: No blockstate file for candlelight:wild_lettuce
	at nl.bramstout.mcworldexporter.model.BlockStateRegistry.getStateFromName(BlockStateRegistry.java:98)
	at nl.bramstout.mcworldexporter.model.BlockStateRegistry.getIdForName(BlockStateRegistry.java:68)
	at nl.bramstout.mcworldexporter.world.Chunk.renderChunkImage(Chunk.java:367)
	at nl.bramstout.mcworldexporter.ui.Renderer2D$LoadChunkTask.run(Renderer2D.java:358)
	at nl.bramstout.mcworldexporter.parallel.ThreadPool$Worker.run(ThreadPool.java:127)
	at java.base/java.lang.Thread.run(Thread.java:840)
java.lang.RuntimeException: Can't find biome data for biome regions_unexplored:cold_river
	at nl.bramstout.mcworldexporter.world.Biome.calculateTints(Biome.java:114)
	at nl.bramstout.mcworldexporter.world.Biome.<init>(Biome.java:54)
	at nl.bramstout.mcworldexporter.world.BiomeRegistry.getBiomeFromName(BiomeRegistry.java:63)
	at nl.bramstout.mcworldexporter.world.BiomeRegistry.getIdForName(BiomeRegistry.java:54)
	at nl.bramstout.mcworldexporter.world.anvil.ChunkAnvil._load(ChunkAnvil.java:208)
	at nl.bramstout.mcworldexporter.world.Chunk.load(Chunk.java:191)
	at nl.bramstout.mcworldexporter.ui.Renderer2D$LoadChunkTask.run(Renderer2D.java:357)
	at nl.bramstout.mcworldexporter.parallel.ThreadPool$Worker.run(ThreadPool.java:127)
	at java.base/java.lang.Thread.run(Thread.java:840)
java.lang.RuntimeException: Can't find biome data for biome terralith:cave/deep_caves
	at nl.bramstout.mcworldexporter.world.Biome.calculateTints(Biome.java:114)
	at nl.bramstout.mcworldexporter.world.Biome.<init>(Biome.java:54)
	at nl.bramstout.mcworldexporter.world.BiomeRegistry.getBiomeFromName(BiomeRegistry.java:63)
	at nl.bramstout.mcworldexporter.world.BiomeRegistry.getIdForName(BiomeRegistry.java:54)
	at nl.bramstout.mcworldexporter.world.anvil.ChunkAnvil._load(ChunkAnvil.java:208)
	at nl.bramstout.mcworldexporter.world.Chunk.load(Chunk.java:191)
	at nl.bramstout.mcworldexporter.ui.Renderer2D$LoadChunkTask.run(Renderer2D.java:357)
	at nl.bramstout.mcworldexporter.parallel.ThreadPool$Worker.run(ThreadPool.java:127)
	at java.base/java.lang.Thread.run(Thread.java:840)
java.lang.RuntimeException: Can't find biome data for biome regions_unexplored:cold_river
	at nl.bramstout.mcworldexporter.world.Biome.calculateTints(Biome.java:114)
	at nl.bramstout.mcworldexporter.world.BiomeRegistry.recalculateTints(BiomeRegistry.java:69)
	at nl.bramstout.mcworldexporter.resourcepack.ResourcePack.setActiveResourcePacks(ResourcePack.java:102)
	at nl.bramstout.mcworldexporter.ui.ResourcePackManager$1.run(ResourcePackManager.java:119)
	at nl.bramstout.mcworldexporter.ui.ResourcePackSelector.synchActiveResourcePacks(ResourcePackSelector.java:258)
	at nl.bramstout.mcworldexporter.ui.ResourcePackSelector.disableResourcePack(ResourcePackSelector.java:180)
	at nl.bramstout.mcworldexporter.ui.ResourcePackSelector$ActiveResourcePack$3.actionPerformed(ResourcePackSelector.java:402)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "String.equalsIgnoreCase(String)" because "method" is null
	at nl.bramstout.mcworldexporter.resourcepack.connectedtextures.OptifineLoader.processFile(OptifineLoader.java:144)
	at nl.bramstout.mcworldexporter.resourcepack.connectedtextures.OptifineLoader.processFolder(OptifineLoader.java:47)
	at nl.bramstout.mcworldexporter.resourcepack.connectedtextures.OptifineLoader.processFolder(OptifineLoader.java:45)
	at nl.bramstout.mcworldexporter.resourcepack.connectedtextures.OptifineLoader.processFolder(OptifineLoader.java:45)
	at nl.bramstout.mcworldexporter.resourcepack.connectedtextures.OptifineLoader.processNamespace(OptifineLoader.java:39)
	at nl.bramstout.mcworldexporter.resourcepack.connectedtextures.OptifineLoader.load(OptifineLoader.java:30)
	at nl.bramstout.mcworldexporter.resourcepack.connectedtextures.ConnectedTextures.load(ConnectedTextures.java:21)
	at nl.bramstout.mcworldexporter.Config.load(Config.java:193)
	at nl.bramstout.mcworldexporter.resourcepack.ResourcePack.setActiveResourcePacks(ResourcePack.java:99)
	at nl.bramstout.mcworldexporter.ui.ResourcePackManager$1.run(ResourcePackManager.java:119)
	at nl.bramstout.mcworldexporter.ui.ResourcePackSelector.synchActiveResourcePacks(ResourcePackSelector.java:258)
	at nl.bramstout.mcworldexporter.ui.ResourcePackSelector.enableResourcePack(ResourcePackSelector.java:163)
	at nl.bramstout.mcworldexporter.ui.ResourcePackSelector$AvailableResourcePack$1.actionPerformed(ResourcePackSelector.java:306)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

Now that happens every time when i remove resource pack or add one, even usdPreviewSurface, happened after reload button.

[my resource pack placement is 1. usdpreview surface 2. my modpack's exported assets to find the biome data 3. stay true ERROR HAPPENS HERE]

**Comment by BramStout** [comment]
This has now been fixed in the latest version of MiEx, which you can get here: https://github.com/BramStoutProductions/MiEx/releases/tag/v1.6.1
